# Generated by Django 4.2.5 on 2023-10-09 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="curator",
            new_name="teacher",
        ),
    ]
