# Generated by Django 4.2.5 on 2023-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
