# Generated by Django 4.2.5 on 2023-10-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
    ]
