# Generated by Django 4.2.5 on 2023-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_teacher_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(to="myapp.student"),
        ),
    ]
