# Generated by Django 4.2.5 on 2023-10-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_group_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
